services:
  - type: web
    name: timecash-king-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: timecash-king-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://seu-frontend.vercel.app
      - key: PORT
        value: 10000

databases:
  - name: timecash-king-db
    plan: free